name: shared_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  firebase_repositories:
    path: "../firebase_repositories"
  intl: ^0.20.1
  uuid: ^4.5.1
  # path: ^1.8.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  mocktail: ^1.0.4
  test: ^1.24.0
